name: 'Create a versioning branch'
description: 'Create a version branch to include additional versioning resources and commits.'
inputs:
  github-token:
    description: >-
      The GitHub token to authorize actions on behalf of users.
    required: true
  version-type:
    description: >-
      The type of the semver version. Accepted inputs: major, minor, patch.
    required: true
    default: patch
  prerelease:
    description: >-
      A boolean indicator for creating a prerelease. GitHub 'pre-release' flag will also be set
      accordingly. Accepted inputs: true, false.
    required: false
    default: 'false'
  pre-id:
    description: >-
      A valid semver pre-release id to bump version to a pre-release version with the specific id.
    required: false
  version-branch-prefix:
    description: >-
      The prefix for the version branch name so the branch name will become
      <prefix><version>. e.g. rel_1.0.0-candidate.1
    required: true
    default: rel_
outputs:
  version-tag:
    description: The new version tag.
  branch-name:
    description: A boolean indicator for the intension for the GitHub release 'prerelease' flag.
runs:
  using: 'node12'
  main: 'dist/bin/index.js'
