name: 'Create a versioning branch'
description: 'Create a version branch to include additional versioning resources and commits.'
inputs:
  github-token:
    description: >-
      The GitHub token to authorize actions on behalf of users.
    required: true
  base-branch:
    description: >-
      The base branch that a versioning branch will be based.
    required: false
  name-prefix:
    description: >-
      The name prefix to include in the new branch name.
      The new branch name format is: <prefix><version>. Example: Rel_branchv1.0.0-rc.1
      The version will be retrieved from the base-branch, bumped according to the version-level.
    required: false
    default: rel_
  version-level:
    description: >-
      The level of the semver version.
      Accepted inputs: major, minor, patch, and prerelease.
    required: false
  pre-id:
    description: >-
      A valid semver pre-release id to bump version as a pre-release.
      If specified, the versioning behavior will become
      'premajor', 'preminor', 'prepatch', and 'prerelease'.
      GitHub 'pre-release' flag will also be set accordingly.
    required: false
  custom-version:
    description: >-
      The custom version to bump to.
      If specified, it will be used instead of the other versioning parameters.
      It must be a valid semver format.
    required: false
  pr-number:
    description: >-
      The pull request number of the pull request from which information will be extracted
      in order to carry out the post-merged actions for a versioning branch. If this parameter
      is present, this action will only attempt to extract information from the given pull requst
      instead. It no longer creates a versioning branch using the other parameters.
    required: false
outputs:
  base-branch:
    description: The branch that a versioning branch is based.
  base-version:
    description: The version found in the base branch.
  head-branch:
    description: The versioning branch.
  head-version:
    description: The version tag used for the versioning branch.
  is-new-branch:
    description: A boolean indicator for whether the head branch a new branch or existing one.
  is-prerelease:
    description: A boolean indicator for whether the version is considered as a prerelease or not.
runs:
  using: 'node12'
  main: 'dist/bin/index.js'
